# default py4lo.toml file

calc_exe = "C:/Program Files (x86)/LibreOffice 5/program/scalc.exe"
python_exe = "C:/Program Files (x86)/LibreOffice 5/program/python.exe"
default_suffix = "updated"
add_readme = "true"
readme_contact = "add a contact here"
debug_file = "py4lo-debug.ods" 
init_file = "new-project.ods" 
src_dir = "src/main"
test_dir = "src/test"
target_dir = "target"
log_level = "DEBUG"