# default py4lo.toml file

calc_exe = "C:/Program Files (x86)/LibreOffice 6/program/scalc.exe"
python_exe = "C:/Program Files (x86)/LibreOffice 6/program/python.exe"
debug_file = "{py4lo}/py4lo-debug.ods"
init_file = "{py4lo}/new-project.ods"
log_level = "DEBUG"

[src]
inc_dir = "{py4lo}/inc"
lib_dir = "{py4lo}/lib"
src_dir = "{project}/src/main"
src_ignore = [] # list of glob patterns
opt_dir = "{project}/src/opt"
assets_dir = "{project}/src/assets"
assets_ignore = [] # list of glob patterns
test_dir = "{project}/src/test"

[dest]
add_readme = "true"
readme_contact = "add a contact here"
suffix = "updated"
temp_dir = "{project}/target"
dest_dir = "Scripts/python"
assets_dest_dir = "Assets"
