# py4lo_win.toml file

python_version = "3.8"
lo_exe = "C:\\Program Files\\LibreOffice 7\\program\\soffice.exe"
python_exe = "C:\\Program Files\\LibreOffice 7\\program\\python.exe"
log_level = "DEBUG"

[src]
source_ods_file = "{project}/sqlite3.ods"
