# py4lo_win.toml file

python_version = "3.8"
calc_exe = "C:\\Program Files\\LibreOffice 7\\program\\scalc.exe"
python_exe = "C:\\Program Files\\LibreOffice 7\\program\\python.exe"
log_level = "DEBUG"

[src]
source_ods_file = "{project}/sqlite3.ods"
